language: android
sudo: false
notifications:
  email: false

before_install:
  - yes | sdkmanager "platforms;android-27"

script: ./CI/travis.sh

android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - tools
    - android-27
    
    jobs:
  include:
    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "strikersix23"
      - git config --local user.email "10016489@discoverers.org"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $da3a8920f94ef7a5b8e03334c52dd88305c6acce
        skip_cleanup: true
        on:
          tags: true
         
