language: android
sudo: false
notifications:
  email: false

before_install:
  - yes | sdkmanager "platforms;android-27"

script: ./CI/travis.sh

android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - tools
    - android-27
    
    jobs:
  include:
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $da3a8920f94ef7a5b8e03334c52dd88305c6acce
        skip_cleanup: true
        on:
          tags: true
